# Generated by Django 6.0 on 2026-04-14 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=120)),
                ('job_type', models.CharField(blank=True, default='', max_length=50)),
                ('source_url', models.URLField()),
                ('description', models.TextField()),
                ('required_skills', models.JSONField(blank=True, default=list)),
                ('match_score', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('analyzed', 'Analyzed'), ('applied', 'Applied'), ('rejected', 'Rejected')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(blank=True, default='')),
                ('outreach_message', models.TextField(blank=True, default='')),
                ('draft_status', models.CharField(choices=[('pending', 'Pending'), ('generated', 'Generated'), ('sent', 'Sent')], default='pending', max_length=20)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application_draft', to='core.jobposting')),
            ],
        ),
    ]
