# Generated by Django 6.0 on 2026-04-09 13:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('delivery_address', models.CharField()),
            ],
        ),
    ]
